### ISSUE TITLE
Navigate to proper page after user creates a collection and updates the metadata.

### ISSUE THREAD

**Issue by hamidra** [SaltyCucumber/assets-portal#26]
Current behavior:
When user creates a collection the page/view does not change which is confusing.

Expected:
When user creates a collection and submits the uploads the page should redirect to a proper page to let them take the next action, or see the result (e.g. the collection page to view the NFTs or a form to ask them to create an instance).

**Comment by VadimSaveljev** [comment]
Fixed in https://github.com/SaltyCucumber/assets-portal/pull/28
