### ISSUE TITLE
Proper error handling for the app and forms.

### ISSUE THREAD

**Issue by hamidra** [SaltyCucumber/assets-portal#27]
When there is an error with submitting transactions, the app would not notify the user of errors issues.
There should be some notification or alert to notify the user of errors.

Also adding an error boundary would help to catch any unexpected errors or crashes
https://reactjs.org/docs/error-boundaries.html

**Comment by VadimSaveljev** [comment]
First part is fixed in https://github.com/SaltyCucumber/assets-portal/pull/28

Will add error boundaries to TODO list in roadmap, so closing for now
