### ISSUE TITLE
Mint an NFT and set metadata in one batch transaction

### ISSUE THREAD

**Issue by gilescope** [SaltyCucumber/assets-portal#41]
Given it takes 12 seconds to mint an NFT and then another 12 seconds for the uploading of the metadata, it would be nice if as a user I could provide all the data in one go and then press mint - that way we'd only have to wait for one transaction to land.

**Comment by jsidorenko** [comment]
Agree! Though it's not the case for the collection's metadata since we don't know the ID until the tx gets mined.
But for the items, the upload should happen on the same screen and user should submit a batched tx

**Comment by gilescope** [comment]
Yeah we kinda need to support variables so these kinds of things can be
specified in one transaction. Could see that being really really helpful if
your doing something via xcm.

**Comment by VadimSaveljev** [comment]
granted in https://github.com/SaltyCucumber/assets-portal/pull/51
