### ISSUE TITLE
no extension detected on linux firefox

### ISSUE THREAD

**Issue by gilescope** [SaltyCucumber/assets-portal#43]
![image](https://user-images.githubusercontent.com/803976/224672646-1b93ab2a-6b17-4847-9963-f3c5b7ee7978.png)

On linux / firefox it can't seem to detect an extension. I have metamask, parity signer and polkadot-js extensions installed so 2 of them ought to show up.

(I know this is a niche platform...)

**Comment by VadimSaveljev** [comment]
Fixed in #73
