### ISSUE TITLE
cache invalidation does not happen when switching networks

### ISSUE THREAD

**Issue by gilescope** [SaltyCucumber/assets-portal#81]
reproduction:
1. Go to 
https://assets-portal.netlify.app/discover/tokens
on westmint, it caches the assets for speed next time which is great, 
2. if I then go to https://assets-portal.netlify.app/discover/drops and 
3. change the network to localhost and then 
4. click on tokens then I can see all the westmint tokens even though I should be looking at a different network.

**Comment by VadimSaveljev** [comment]
tokens are no longer part of the project
